/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kxupkyrnegbpwhmkvmji"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dXBreXJuZWdicHdobWt2bWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxODcxMDgsImV4cCI6MjA4NTc2MzEwOH0.guJosdF1W-ieWfAdE3RThdhMrU7P0Xz_S-pp8CABCiQ"