from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Enum, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base
import enum


class PoCType(str, enum.Enum):
    REAL_POC = "real_poc"
    POOR_POC = "poor_poc"


class PoC(Base):
    """PoC (Proof of Concept) for True Positive vulnerabilities only.
    
    Workflow:
    1. LLM Analyst Module generates PoC ONLY for True Positive vulnerabilities
    2. Sandbox Module tests the PoC to verify exploit success
    3. Classification based on Sandbox result:
       - Exploit successful → Real PoC
       - Exploit failed → Poor PoC
    """
    __tablename__ = "pocs"
    
    id = Column(Integer, primary_key=True, index=True)
    vulnerability_id = Column(Integer, ForeignKey("vulnerabilities.id"), nullable=False)
    
    # PoC Info (Generated by LLM)
    poc_type = Column(Enum(PoCType), nullable=False)  # LLM classifies as real_poc or poor_poc
    poc_name = Column(String(255), nullable=False)
    
    # File Paths (LLM output files)
    # Real PoC: C:\tmp\{project_name}\TP\PoC\Real_PoC\{file_name}
    # Poor PoC: C:\tmp\{project_name}\TP\PoC\Poor_PoC\{file_name}
    poc_path = Column(String(500), nullable=False)
    
    # Sandbox Verification (TODO: Integrate Sandbox Module)
    sandbox_tested = Column(Boolean, default=False)  # Has been tested in sandbox
    exploit_successful = Column(Boolean, nullable=True)  # True = Real PoC, False = Poor PoC
    sandbox_result = Column(Text, nullable=True)  # Sandbox test output/logs
    sandbox_tested_at = Column(DateTime(timezone=True), nullable=True)
    
    # Metadata
    file_size = Column(Integer, nullable=True)  # Size in bytes
    is_downloadable = Column(Boolean, default=True)
    description = Column(String(500), nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    vulnerability = relationship("Vulnerability", back_populates="pocs")
